### PR TITLE
Import static snapshot of MOGUL

### PR DESCRIPTION
**Pull request by doublec**
This is a static snapshot of MOGUL. It's the latest I could retrieve from the internet archive. It places it in the same root URL as it used to be on the old site and adjusts all the internal URLs. It provides all the packages that used to exist.

I'm not sure this is the best way of providing a MOGUL snapshot - it adds 130MB to the checked out source, or about 50MB to the git clone. It does provide a convenient way of accessing MOGUL until some other approach (maybe a reimplementation using Roads?) is done.

### CODE REVIEW

**Comment by sjmackenzie** [comment]
I just received this email:

```
The page build failed for the `master` branch with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

**Comment by doublec** [comment]
Odd, I tested locally with Jekyll. I wonder if it's too big? Can we get a log?

**Comment by sjmackenzie** [comment]
Hmm seems that's all the info available to us. The links in the email contain further information.

**Comment by doublec** [comment]
It says that build failure messages are viewable in the repository settings, under "Github pages". Are you able to access that?

**Comment by sjmackenzie** [comment]
```
Your site is having problems building: Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.
```

That's all it says... what an obtuse piece of software.

**Comment by doublec** [comment]
I've installed github pages locally and it gives a bunch of deprecation and errors. I think it may be we are out of date for current github pages and the existing site won't even build. I'm trying to fix things up.

**Comment by doublec** [comment]
See pull request #8 for hopefully a fix.

**Pull request merged**
